<?xml version="1.0" encoding="UTF-8"?>
<definitions name="SaferPassengerManagerPort.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="urn://Traveller/"
    targetNamespace="urn://Traveller/">

  <types>
    <xsd:schema>
      <xsd:import namespace="urn://Traveller/"
          schemaLocation="SaferPassengerManagerSchema.xsd"/>
    </xsd:schema>
  </types>

  <message name="addPassengerRequest">
    <part name="parameters" element="tns:addPassenger"/>
  </message>
  <message name="addPassengerResponse">
    <part name="parameters" element="tns:addPassengerResponse"/>
  </message>
<message name="addPassengerFault">
  <part name="parameters" element="tns:addPassengerFault"/>
</message>
<portType name="SaferPassengerManager">
  <operation name="addPassenger">
    <input name="input1" message="tns:addPassengerRequest"/>
    <output name="out1" message="tns:addPassengerResponse"/>
    <fault name="fault1" message="tns:addPassengerFault"/>
  </operation>
</portType>
</definitions>
